SELECT DISTINCT COMPANY FROM `MANUFACTURER`

SELECT COUNT(COMPANY) AS total FROM `MANUFACTURER;

SELECT DISTINCT WARE FROM `CATEGORY` WHERE CLASS = 'Food'

SELECT DISTINCT COMPANY FROM `MANUFACTURER` WHERE COMPANY LIKE 'A%' OR COMPANY LIKE 'B%' ORDER BY COMPANY

SELECT DISTINCT WARE FROM `PRODUCT` 
WHERE WARE NOT IN (
	SELECT WARE
	FROM `MATERIAL`
);

SELECT DISTINCT WARE FROM `CATEGORY`
WHERE WARE NOT IN (
	SELECT WARE
	FROM `PRODUCT`
);

SELECT DISTINCT WARE FROM `CATEGORY`
WHERE WARE IN (
	SELECT WARE
	FROM `PRODUCT`
) 
AND WARE IN (
	SELECT WARE
	FROM `MATERIAL`
);

SELECT MIN(PRICE) AS min_price, MAX(PRICE) AS max_price
FROM `PRODUCT`
WHERE WARE = 'Paper';


SELECT 
	ROUND(AVG(PRICE), 1) AS avg_price,
	ROUND(SUM((PRICE - (SELECT AVG(PRICE) 
	FROM `PRODUCT` 
	WHERE WARE = 'Meat')) * 
	(PRICE - (SELECT AVG(PRICE) 
	FROM `PRODUCT`
	WHERE WARE = 'Meat'))) / (COUNT(PRICE)), 1) AS variance_price
FROM `PRODUCT`
WHERE WARE = 'Meat';