-- 4.1
SELECT prod, AveragePrice
FROM (
  SELECT PRODUCT.WARE AS prod, AVG(price) AS AveragePrice
  FROM `PRODUCT`
  GROUP BY PRODUCT.WARE
)
WHERE AveragePrice = (
  SELECT MAX(AveragePrice)
  FROM (
    SELECT AVG(price) AS AveragePrice
    FROM `PRODUCT`
    GROUP BY PRODUCT.WARE
  )
);

-- 4.2
SELECT cat, ware
FROM (
  SELECT CATEGORY.CLASS AS cat, PRODUCT.WARE as ware
  FROM `CATEGORY`
  INNER JOIN PRODUCT
  ON CATEGORY.WARE = PRODUCT.WARE
  GROUP BY cat
 );
 
-- 4.3
SELECT cat, ware, price
FROM (
  SELECT CATEGORY.CLASS AS cat, PRODUCT.WARE as ware, PRODUCT.PRICE as price
  FROM `CATEGORY`
  INNER JOIN PRODUCT
  ON CATEGORY.WARE = PRODUCT.WARE
  GROUP BY cat
  HAVING MAX(price)
 );
 
-- 4.4
SELECT DISTINCT comp
FROM (
	SELECT MANUFACTURER.COMPANY as comp 
	FROM `MANUFACTURER`
)
WHERE comp NOT IN (
	SELECT MANUFACTURER.COMPANY as comp
	FROM `MANUFACTURER`
	INNER JOIN `PRODUCT`
	ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
	INNER JOIN (
		SELECT AVG(PRODUCT.PRICE) * 1.2 AS ave, PRODUCT.WARE
		FROM `PRODUCT`
		GROUP BY PRODUCT.WARE
	) AS average_table
	ON average_table.WARE = PRODUCT.WARE
	GROUP BY comp, PRODUCT.WARE
	HAVING PRODUCT.PRICE <= ave
)
ORDER BY comp;

-- 4.5
SELECT MANUFACTURER.COMPANY, CATEGORY.CLASS, group_concat(PRODUCT.WARE)
FROM MANUFACTURER 
INNER JOIN PRODUCT ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
INNER JOIN CATEGORY ON PRODUCT.WARE = CATEGORY.WARE
GROUP BY MANUFACTURER.COMPANY, CATEGORY.CLASS
HAVING COUNT(DISTINCT CATEGORY.WARE) = (
    SELECT COUNT(DISTINCT c2.WARE)
    FROM CATEGORY c2
    WHERE c2.CLASS = CATEGORY.CLASS
)
ORDER BY CATEGORY.CLASS;

-- 4.6
SELECT MANUFACTURER.BILL_ID AS bill, MANUFACTURER.COMPANY AS comp, 
       (SELECT GROUP_CONCAT(DISTINCT MATERIAL.WARE) 
	   FROM MATERIAL WHERE MATERIAL.BILL_ID = MANUFACTURER.BILL_ID) AS mat, 
       (SELECT GROUP_CONCAT(DISTINCT PRODUCT.WARE) 
	   FROM PRODUCT WHERE PRODUCT.BILL_ID = MANUFACTURER.BILL_ID) AS prod, 
       (SELECT SUM(PRODUCT.PRICE * PRODUCT.AMOUNT) 
	   FROM PRODUCT WHERE PRODUCT.BILL_ID = MANUFACTURER.BILL_ID) AS price
FROM MANUFACTURER
ORDER BY MANUFACTURER.COMPANY;

-- 4.7

-- 4.8
SELECT comp, wares
FROM (
	SELECT MANUFACTURER.COMPANY AS comp, group_concat(DISTINCT PRODUCT.WARE) AS wares
	FROM MANUFACTURER
	INNER JOIN PRODUCT ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
	GROUP BY MANUFACTURER.COMPANY
	HAVING COUNT(DISTINCT PRODUCT.WARE) = 7
);