-- 1.1
SELECT DISTINCT COMPANY FROM `MANUFACTURER`;

-- 1.2
SELECT COUNT(COMPANY) AS total FROM `MANUFACTURER`;

-- 1.3
SELECT DISTINCT WARE FROM `CATEGORY` WHERE CLASS = 'Food';

-- 1.4
SELECT DISTINCT COMPANY FROM `MANUFACTURER` WHERE COMPANY LIKE 'A%' OR COMPANY LIKE 'B%' ORDER BY COMPANY;

-- 1.5
SELECT DISTINCT WARE FROM `PRODUCT` 
EXCEPT
SELECT DISTINCT WARE FROM `MATERIAL`;

-- 1.6
SELECT DISTINCT WARE FROM `MATERIAL`
EXCEPT
SELECT DISTINCT WARE FROM `PRODUCT`;

-- 1.7
SELECT DISTINCT WARE FROM `MATERIAL`
INTERSECT
SELECT DISTINCT WARE FROM `PRODUCT`;

-- 1.8
SELECT MIN(PRICE) AS min_price, MAX(PRICE) AS max_price
FROM `PRODUCT`
WHERE WARE = 'Paper';

-- 1.9
SELECT  ROUND(AVG(PRICE), 1) AS avg_price,
	ROUND(SUM(Price * Price) / COUNT(Price) - (SUM(Price) / COUNT(Price)) * (SUM(Price) / COUNT(Price)), 1) AS Variance_Price
FROM PRODUCT
WHERE WARE = 'Meat';