-- 2.1
SELECT DISTINCT COMPANY FROM `MANUFACTURER`
INNER JOIN PRODUCT 
ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
WHERE PRODUCT.WARE = 'Drinking water'
ORDER BY COMPANY;

-- 2.2
SELECT DISTINCT MANUFACTURER.COMPANY AS COMPANY, PRODUCT.WARE AS WARE
FROM MANUFACTURER
INNER JOIN PRODUCT
ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
INNER JOIN CATEGORY 
ON CATEGORY.WARE = PRODUCT.WARE
WHERE CATEGORY.CLASS = 'Raw food'
ORDER BY PRODUCT.WARE, MANUFACTURER.COMPANY;

-- 2.3
SELECT DISTINCT PRODUCT.WARE 
FROM PRODUCT
INNER JOIN MATERIAL 
ON PRODUCT.BILL_ID = MATERIAL.BILL_ID
INNER JOIN CATEGORY 
ON MATERIAL.WARE = CATEGORY.WARE 
AND CATEGORY.CLASS = 'Mineral'
ORDER BY PRODUCT.WARE;

-- 2.4
SELECT DISTINCT MANUFACTURER.COMPANY AS COMPANY
FROM MANUFACTURER
INNER JOIN PRODUCT
ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
INNER JOIN CATEGORY 
ON CATEGORY.WARE = PRODUCT.WARE
WHERE CATEGORY.CLASS = 'Fuel'

INTERSECT

SELECT DISTINCT MANUFACTURER.COMPANY AS COMPANY
FROM MANUFACTURER
INNER JOIN PRODUCT
ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
INNER JOIN CATEGORY 
ON CATEGORY.WARE = PRODUCT.WARE
WHERE CATEGORY.CLASS = 'Food';

-- 2.5

SELECT DISTINCT FUEL_MAN.COMPANY, FUEL_PROD.WARE, FOOD_PROD.WARE 
FROM MANUFACTURER AS FUEL_MAN
INNER JOIN PRODUCT AS FUEL_PROD 
ON FUEL_PROD.BILL_ID = FUEL_MAN.BILL_ID 
INNER JOIN CATEGORY AS FUEL_CAT 
ON FUEL_PROD.WARE = FUEL_CAT.WARE 
AND FUEL_CAT.CLASS = "Fuel" 
INNER JOIN MANUFACTURER AS FOOD_MAN 
ON FOOD_MAN.COMPANY = FUEL_MAN.COMPANY
INNER JOIN PRODUCT AS FOOD_PROD 
ON FOOD_MAN.BILL_ID = FOOD_PROD.BILL_ID 
INNER JOIN CATEGORY AS FOOD_CATEGORY 
ON FOOD_PROD.WARE = FOOD_CATEGORY.WARE 
AND FOOD_CATEGORY.CLASS = "Food";

-- 2.6

SELECT DISTINCT MAN1.COMPANY
FROM MANUFACTURER AS MAN1
INNER JOIN PRODUCT AS PROD1 
ON MAN1.BILL_ID = PROD1.BILL_ID
INNER JOIN CATEGORY AS CAT1 
ON PROD1.WARE = CAT1.WARE
INNER JOIN MANUFACTURER AS MAN2 
ON MAN1.COMPANY = MAN2.COMPANY
INNER JOIN PRODUCT AS PROD2 
ON MAN2.BILL_ID = PROD2.BILL_ID
INNER JOIN CATEGORY AS CAT2 
ON PROD2.WARE = CAT2.WARE
WHERE CAT1.CLASS == CAT2.CLASS 
AND PROD1.WARE <> PROD2.WARE
ORDER BY MAN1.COMPANY;